services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    #stdin_open: True
    #tty: true
    volumes:
      - ./backend:/app
      #- ./.pgpass:/app/.pgpass
      # - ./.pg_service.conf:/root/.pg_service.conf
    ports:
      - "8000:8000"
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
